import type { MealType, SourceType } from "./types";

export const CHIPS = [
  "natural wine bar",
  "chef's counter",
  "tasting menu",
  "hole in the wall",
  "market stall",
  "rooftop",
  "date night",
  "long boozy lunch",
  "low-key breakfast",
  "loud and social",
  "quiet and refined",
  "local institution",
  "new opening",
  "great cocktails",
  "vegetarian-friendly",
  "outdoor seating",
];

export const SOURCE_TYPES: SourceType[] = [
  "friend rec",
  "my own list",
  "blog / press",
  "saved from social",
];

export const SOURCE_TRUST: Record<SourceType, number> = {
  "friend rec": 20,
  "my own list": 15,
  "blog / press": 10,
  "suggested by Mise": 8,
  "saved from social": 5,
};

// phrase -> chip vocabulary
export const VIBE_KEYWORDS: Array<[string, string]> = [
  ["natural wine", "natural wine bar"],
  ["orange wine", "natural wine bar"],
  ["vinos naturales", "natural wine bar"],
  ["wine bar", "natural wine bar"],
  ["counter seat", "chef's counter"],
  ["counter seats", "chef's counter"],
  ["at the counter", "chef's counter"],
  ["omakase", "chef's counter"],
  ["barra", "chef's counter"],
  ["tasting menu", "tasting menu"],
  ["menu degustación", "tasting menu"],
  ["degustation", "tasting menu"],
  ["prix fixe", "tasting menu"],
  ["hole in the wall", "hole in the wall"],
  ["tacos al pastor", "hole in the wall"],
  ["al pastor", "hole in the wall"],
  ["taquería", "hole in the wall"],
  ["taqueria", "hole in the wall"],
  ["street food", "hole in the wall"],
  ["puesto", "hole in the wall"],
  ["market stall", "market stall"],
  ["mercado", "market stall"],
  ["market", "market stall"],
  ["rooftop", "rooftop"],
  ["terrace", "rooftop"],
  ["azotea", "rooftop"],
  ["date night", "date night"],
  ["romantic", "date night"],
  ["special occasion", "date night"],
  ["long lunch", "long boozy lunch"],
  ["boozy", "long boozy lunch"],
  ["comida corrida", "long boozy lunch"],
  ["sobremesa", "long boozy lunch"],
  ["breakfast", "low-key breakfast"],
  ["desayuno", "low-key breakfast"],
  ["brunch", "low-key breakfast"],
  ["pastries", "low-key breakfast"],
  ["bakery", "low-key breakfast"],
  ["panadería", "low-key breakfast"],
  ["loud", "loud and social"],
  ["packed", "loud and social"],
  ["party", "loud and social"],
  ["buzzy", "loud and social"],
  ["quiet", "quiet and refined"],
  ["refined", "quiet and refined"],
  ["elegant", "quiet and refined"],
  ["calm", "quiet and refined"],
  ["institution", "local institution"],
  ["been there forever", "local institution"],
  ["classic", "local institution"],
  ["since 19", "local institution"],
  ["clásico", "local institution"],
  ["new opening", "new opening"],
  ["just opened", "new opening"],
  ["newly opened", "new opening"],
  ["opened last", "new opening"],
  ["cocktail", "great cocktails"],
  ["mezcal", "great cocktails"],
  ["mezcalería", "great cocktails"],
  ["mixology", "great cocktails"],
  ["vegetarian", "vegetarian-friendly"],
  ["vegan", "vegetarian-friendly"],
  ["veggie", "vegetarian-friendly"],
  ["outdoor", "outdoor seating"],
  ["patio", "outdoor seating"],
  ["sidewalk", "outdoor seating"],
  ["garden", "outdoor seating"],
];

export const MEAL_KEYWORDS: Array<[string, MealType]> = [
  ["breakfast", "breakfast"],
  ["desayuno", "breakfast"],
  ["brunch", "breakfast"],
  ["pastries", "breakfast"],
  ["bakery", "breakfast"],
  ["panadería", "breakfast"],
  ["lunch", "lunch"],
  ["comida", "lunch"],
  ["almuerzo", "lunch"],
  ["dinner", "dinner"],
  ["cena", "dinner"],
  ["tasting menu", "dinner"],
  ["cocktails", "drinks"],
  ["mezcalería", "drinks"],
  ["cantina", "drinks"],
  ["bar", "drinks"],
  ["nightcap", "drinks"],
];

export const CUISINE_KEYWORDS: Array<[string, string]> = [
  ["taco", "tacos"],
  ["pastor", "tacos"],
  ["taquería", "tacos"],
  ["seafood", "seafood"],
  ["mariscos", "seafood"],
  ["tostada", "seafood"],
  ["ceviche", "seafood"],
  ["sushi", "japanese"],
  ["omakase", "japanese"],
  ["ramen", "japanese"],
  ["pasta", "italian"],
  ["trattoria", "italian"],
  ["pizza", "italian"],
  ["bakery", "bakery"],
  ["panadería", "bakery"],
  ["pastry", "bakery"],
  ["barbacoa", "barbacoa"],
  ["oaxac", "oaxacan"],
  ["yucat", "yucatecan"],
  ["mole", "contemporary mexican"],
  ["contemporary", "contemporary mexican"],
  ["korean", "korean"],
  ["chinese", "chinese"],
  ["french", "french"],
  ["bistro", "french"],
  ["cocktail", "bar"],
  ["mezcal", "bar"],
  ["wine", "wine"],
];

export const PRICE_WORDS: Array<[string, number]> = [
  ["cheap", 1],
  ["street", 1],
  ["taquería", 1],
  ["taqueria", 1],
  ["barato", 1],
  ["splurge", 4],
  ["expensive", 4],
  ["special occasion", 4],
  ["blow-out", 4],
  ["pricey", 3],
];

export const SLOT_TEMPLATE: Array<{
  meal: MealType;
  start: string;
  end: string;
  optional: boolean;
}> = [
  { meal: "breakfast", start: "09:00", end: "10:30", optional: true },
  { meal: "lunch", start: "14:00", end: "16:00", optional: false },
  { meal: "dinner", start: "20:00", end: "22:30", optional: false },
  { meal: "drinks", start: "22:45", end: "00:30", optional: true },
];

export const MEAL_LABEL: Record<MealType, string> = {
  breakfast: "Breakfast",
  lunch: "Lunch",
  dinner: "Dinner",
  drinks: "Drinks",
};

export const PARTY_TAG_BOOST: Record<string, string[]> = {
  solo: ["chef's counter", "hole in the wall", "market stall", "quiet and refined"],
  partner: ["date night", "quiet and refined", "natural wine bar", "tasting menu"],
  "friends group": ["loud and social", "long boozy lunch", "great cocktails", "rooftop"],
  family: ["local institution", "outdoor seating", "market stall", "low-key breakfast"],
};
